# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"
services:
  composer:
    image: composer:1.9
    volumes:
      - ./:/app:cached
  codacy:
    image: codacy/codacy-analysis-cli:latest
    environment:
      CODACY_CODE: /app
    volumes:
      - ./:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
  gesso:
    build: ./
    init: true
    volumes:
      - ./images:/app/images:cached
      - ./js:/app/js:cached
      - ./source:/app/source:cached
      - type: volume
        source: gesso-pattern-lab
        target: /app/pattern-lab
      - type: volume
        source: gesso-css
        target: /app/css
volumes:
  {}
